// static data - no db import
import type {
  NewCategory,
  NewProduct,
  NewStoreSettings,
} from "@/db/schema";


const USD_TO_LYD = 5.5;

function toLyd(amount: number): number {
  return Math.round(amount * USD_TO_LYD * 100) / 100;
}

function toLydOrNull(amount: number | null | undefined): number | null {
  if (amount === null || amount === undefined) return null;
  return toLyd(amount);
}

export const INITIAL_CATEGORIES: NewCategory[] = [
  {
    slug: "notebooks",
    nameEn: "Notebooks & Paper Goods",
    nameAr: "الدفاتر والمنتجات الورقية",
    descriptionEn: "100gsm fountain-pen friendly notebooks, dotted journals, academic pads & archival A4 paper.",
    descriptionAr: "دفاتر ملاحظات فاخرة بوزن 100 جرام، دفاتر منقطة، كراسات أكاديمية وورق A4 عالي الجودة.",
    imageUrl: "/images/category-illustrations/notebooks.webp",
    badgeEn: "100–120 GSM Paper",
    badgeAr: "ورق فاخر 120 جرام",
    sortOrder: 1,
  },
  {
    slug: "writing",
    nameEn: "Fine Writing & Pens",
    nameAr: "أدوات الكتابة والأقلام الفاخرة",
    descriptionEn: "Precision fountain pens, Japanese gel rollers, architectural fineliners & pastel highlighters.",
    descriptionAr: "أقلام حبر سائلة دقيقة، أقلام جل يابانية، محددات هندسية وأقلام تظليل بألوان الباستيل.",
    imageUrl: "/images/category-illustrations/writing.webp",
    badgeEn: "Precision Nib",
    badgeAr: "كتابة فائقة الدقة",
    sortOrder: 2,
  },
  {
    slug: "bags",
    nameEn: "School Bags & Organizers",
    nameAr: "الحقائب المدرسية وحلول التنظيم",
    descriptionEn: "Ergonomic waterproof backpacks, padded laptop sleeves, canvas pen cases & modular desk trays.",
    descriptionAr: "حقائب ظهر مدرسية مريحة ومقاومة للماء، حافظات حاسوب مبطنة، مقلمات قماشية ومنظمات مكتبية.",
    imageUrl: "/images/category-illustrations/bags.webp",
    badgeEn: "Ergonomic Series",
    badgeAr: "تصميم مريح للظهر",
    sortOrder: 3,
  },
  {
    slug: "it-peripherals",
    nameEn: "IT Peripherals & Accessories",
    nameAr: "ملحقات الحاسوب والتقنية",
    descriptionEn: "Wireless mechanical keyboards, ergonomic silent mice, USB-C 10-in-1 hubs & NVMe portable SSDs.",
    descriptionAr: "لوحات مفاتيح ميكانيكية لاسلكية، فئران مريحة صامتة، موزعات USB-C وأقراص تخزين SSD سريعة.",
    imageUrl: "/images/category-illustrations/it-accessories.webp",
    badgeEn: "Pro Studio Tech",
    badgeAr: "تقنيات احترافية",
    sortOrder: 4,
  },
  {
    slug: "ink-consumables",
    nameEn: "Ink, Toner & Consumables",
    nameAr: "الأحبار والتونر والمستهلكات",
    descriptionEn: "High-yield laser toner cartridges, pigment ink bottles, thermal labels & studio paper reams.",
    descriptionAr: "خراطيش تونر ليزر عالية الإنتاجية، عبوات حبر ملونة، ملصقات حرارية ورزم ورق للمكاتب.",
    imageUrl: "/images/category-illustrations/ink-toner.webp",
    badgeEn: "High-Yield OEM",
    badgeAr: "إنتاجية طباعة عالية",
    sortOrder: 5,
  },
  {
    slug: "art-drafting",
    nameEn: "Art & Technical Drafting",
    nameAr: "الفنون الجميلة والرسم الهندسي",
    descriptionEn: "Dual-tip alcohol markers, brass drafting compass sets, watercolor brush pens & heavy sketchbooks.",
    descriptionAr: "أقلام ماركر مزدوجة الرأس، أطقم فرجار هندسي نحاسي، أقلام ألوان مائية وكراسات رسم سميكة.",
    imageUrl: "/images/category-illustrations/art-drafting.webp",
    badgeEn: "Studio Grade",
    badgeAr: "درجة استوديو فنية",
    sortOrder: 6,
  },
  {
    slug: "calculators-tech",
    nameEn: "Calculators & Desk Tech",
    nameAr: "الآلات الحاسبة وإلكترونيات المكتب",
    descriptionEn: "Scientific graphing calculators, solar financial calculators, LED desk lamps & Pomodoro timers.",
    descriptionAr: "آلات حاسبة علمية وبيانية، حاسبات مكتبية بالطاقة الشمسية، مصابيح LED ذكية ومؤقتات الدراسة.",
    imageUrl: "/images/category-illustrations/calculators.webp",
    badgeEn: "Exam Approved",
    badgeAr: "معتمدة للامتحانات",
    sortOrder: 7,
  },
  // ─── SUBCATEGORIES ───────────────────────────────────────────────────
  // 1. Notebooks subcategories
  {
    slug: "dotted-journals",
    parentSlug: "notebooks",
    nameEn: "Dotted Journals",
    nameAr: "دفاتر منقطة",
    descriptionEn: "Premium dotted journals for bullet journaling and creative note-taking.",
    descriptionAr: "دفاتر منقطة فاخرة لتقنية بوليت jornal والملاحظات الإبداعية.",
    imageUrl: "/images/category-illustrations/notebooks.webp",
    badgeEn: "Bullet Journal",
    badgeAr: "بوليت jornal",
    sortOrder: 11,
  },
  {
    slug: "grid-notebooks",
    parentSlug: "notebooks",
    nameEn: "Grid Notebooks",
    nameAr: "دفاتر مربعات",
    descriptionEn: "Twin-wire and spiral grid notebooks for academic and STEM notes.",
    descriptionAr: "دفاتر مربعات بسلك مزدوج ولولبية للملاحظات الأكاديمية والعلمية.",
    imageUrl: "/images/category-illustrations/notebooks.webp",
    badgeEn: "Academic",
    badgeAr: "أكاديمي",
    sortOrder: 12,
  },
  {
    slug: "planners-organizers",
    parentSlug: "notebooks",
    nameEn: "Planners & Organizers",
    nameAr: "مخططات ومنظمات",
    descriptionEn: "Weekly planners, desk pads, and sticky note folios for productivity.",
    descriptionAr: "مخططات أسبوعية ومنظمات مكتبية وملاحظات لاصقة لتعزيز الإنتاجية.",
    imageUrl: "/images/category-illustrations/notebooks.webp",
    badgeEn: "Productivity",
    badgeAr: "إنتاجية",
    sortOrder: 13,
  },

  // 2. Writing subcategories
  {
    slug: "fountain-pens",
    parentSlug: "writing",
    nameEn: "Fountain Pens",
    nameAr: "أقلام حبر سائل",
    descriptionEn: "Fine nib fountain pens with premium German engineering.",
    descriptionAr: "أقلام حبر سائل بريشة دقيقة وهندسة ألمانية فاخرة.",
    imageUrl: "/images/category-illustrations/writing.webp",
    badgeEn: "Fine Nib",
    badgeAr: "ريشة دقيقة",
    sortOrder: 21,
  },
  {
    slug: "gel-rollers",
    parentSlug: "writing",
    nameEn: "Gel Rollers",
    nameAr: "أقلام جل",
    descriptionEn: "Smooth-flow gel ink pens with quick-dry pigment ink.",
    descriptionAr: "أقلام جل سلسة بحبر صبغي سريع الجفاف.",
    imageUrl: "/images/category-illustrations/writing.webp",
    badgeEn: "Smooth Flow",
    badgeAr: "تدفق سلس",
    sortOrder: 22,
  },
  {
    slug: "highlighters",
    parentSlug: "writing",
    nameEn: "Highlighters",
    nameAr: "أقلام تظليل",
    descriptionEn: "Dual-tip pastel highlighters for studying and note organization.",
    descriptionAr: "أقلام تظليل باستيل مزدوجة الرأس للدراسة وتنظيم الملاحظات.",
    imageUrl: "/images/category-illustrations/writing.webp",
    badgeEn: "Pastel",
    badgeAr: "باستيل",
    sortOrder: 23,
  },

  // 3. Bags subcategories
  {
    slug: "backpacks",
    parentSlug: "bags",
    nameEn: "Backpacks",
    nameAr: "حقائب ظهر",
    descriptionEn: "Ergonomic waterproof backpacks with laptop compartments.",
    descriptionAr: "حقائب ظهر مريحة ومقاومة للماء مع جيب للحاسوب.",
    imageUrl: "/images/category-illustrations/bags.webp",
    badgeEn: "Ergonomic",
    badgeAr: "مريح",
    sortOrder: 31,
  },
  {
    slug: "pencil-cases",
    parentSlug: "bags",
    nameEn: "Pencil Cases & Pouches",
    nameAr: "مقلمات وحاويات",
    descriptionEn: "Expandable standing pouches for pens, tech, and accessories.",
    descriptionAr: "مقلمات قابلة للتوسع وقوفاً للأقلام والإكسسوارات التقنية.",
    imageUrl: "/images/category-illustrations/bags.webp",
    badgeEn: "Stand Design",
    badgeAr: "تصميم قائم",
    sortOrder: 32,
  },
  {
    slug: "desk-organizers",
    parentSlug: "bags",
    nameEn: "Desk Organizers",
    nameAr: "منظمات مكتبية",
    descriptionEn: "Modular desktop organizer suites for documents and accessories.",
    descriptionAr: "أنظمة تنظيم مكتبية معيارية للمستندات والإكسسوارات.",
    imageUrl: "/images/category-illustrations/bags.webp",
    badgeEn: "Modular",
    badgeAr: "معيارية",
    sortOrder: 33,
  },

  // 4. IT Peripherals subcategories
  {
    slug: "keyboards",
    parentSlug: "it-peripherals",
    nameEn: "Keyboards",
    nameAr: "لوحات مفاتيح",
    descriptionEn: "Wireless mechanical keyboards with tri-mode connectivity.",
    descriptionAr: "لوحات مفاتيح ميكانيكية لاسلكية بثلاثية الاتصال.",
    imageUrl: "/images/category-illustrations/it-accessories.webp",
    badgeEn: "Mechanical",
    badgeAr: "ميكانيكية",
    sortOrder: 41,
  },
  {
    slug: "mice",
    parentSlug: "it-peripherals",
    nameEn: "Mice",
    nameAr: "فئران",
    descriptionEn: "Ergonomic silent wireless mice with high-DPI sensors.",
    descriptionAr: "فئران لاسلكية صامتة ومريحة بحساسات عالية الدقة.",
    imageUrl: "/images/category-illustrations/it-accessories.webp",
    badgeEn: "Silent Click",
    badgeAr: "نقرات صامتة",
    sortOrder: 42,
  },
  {
    slug: "hubs-adapters",
    parentSlug: "it-peripherals",
    nameEn: "USB Hubs & Adapters",
    nameAr: "موزعات ومحولات USB",
    descriptionEn: "Multi-port aluminum USB-C hubs with HDMI, PD, and NVMe.",
    descriptionAr: "موزعات USB-C ألمنيوم متعددة المنافذ مع HDMI وشحن سريع.",
    imageUrl: "/images/category-illustrations/it-accessories.webp",
    badgeEn: "10-in-1",
    badgeAr: "10 في 1",
    sortOrder: 43,
  },

  // 5. Ink & Consumables subcategories
  {
    slug: "toner-cartridges",
    parentSlug: "ink-consumables",
    nameEn: "Toner Cartridges",
    nameAr: "خراطيش تونر",
    descriptionEn: "High-yield laser toner cartridges with smart chips.",
    descriptionAr: "خراطيش تونر ليزر عالية الإنتاجية مع شرائح ذكية.",
    imageUrl: "/images/category-illustrations/ink-toner.webp",
    badgeEn: "High Yield",
    badgeAr: "إنتاجية عالية",
    sortOrder: 51,
  },
  {
    slug: "ink-refills",
    parentSlug: "ink-consumables",
    nameEn: "Ink Refills",
    nameAr: "عبوات حبر",
    descriptionEn: "Pigment ink refill bottles for EcoTank and continuous ink systems.",
    descriptionAr: "عبوات حبر صبغي لأنظمة إيكو-تانك والأحبار المستمرة.",
    imageUrl: "/images/category-illustrations/ink-toner.webp",
    badgeEn: "CMYK",
    badgeAr: "CMYK",
    sortOrder: 52,
  },
  {
    slug: "paper-reams",
    parentSlug: "ink-consumables",
    nameEn: "Paper Reams",
    nameAr: "رزم ورق",
    descriptionEn: "Ultra-white A4 paper for laser and inkjet printers.",
    descriptionAr: "ورق A4 فائق البياض للطابعات الليزرية والحبرية.",
    imageUrl: "/images/category-illustrations/ink-toner.webp",
    badgeEn: "90 GSM",
    badgeAr: "90 جرام",
    sortOrder: 53,
  },

  // 6. Art & Drafting subcategories
  {
    slug: "art-markers",
    parentSlug: "art-drafting",
    nameEn: "Art Markers",
    nameAr: "أقلام ماركر فنية",
    descriptionEn: "Dual-tip alcohol markers for illustration and design.",
    descriptionAr: "أقلام ماركر كحولية مزدوجة الرأس للرسوم والتصميم.",
    imageUrl: "/images/category-illustrations/art-drafting.webp",
    badgeEn: "48 Colors",
    badgeAr: "48 لوناً",
    sortOrder: 61,
  },
  {
    slug: "geometry-sets",
    parentSlug: "art-drafting",
    nameEn: "Geometry Sets",
    nameAr: "أطقم هندسة",
    descriptionEn: "Professional brass compass and drafting kits.",
    descriptionAr: "أطقم فرجار ورسم هندسي احترافية من النحاس.",
    imageUrl: "/images/category-illustrations/art-drafting.webp",
    badgeEn: "9-Piece",
    badgeAr: "9 قطع",
    sortOrder: 62,
  },
  {
    slug: "sketchpads",
    parentSlug: "art-drafting",
    nameEn: "Sketchpads",
    nameAr: "كراسات رسم",
    descriptionEn: "Heavy-weight watercolor and mixed media sketchpads.",
    descriptionAr: "كراسات رسم ثقيلة للألوان المائية والتقنيات المختلطة.",
    imageUrl: "/images/category-illustrations/art-drafting.webp",
    badgeEn: "300 GSM",
    badgeAr: "300 جرام",
    sortOrder: 63,
  },

  // 7. Calculators & Desk Tech subcategories
  {
    slug: "scientific-calculators",
    parentSlug: "calculators-tech",
    nameEn: "Scientific Calculators",
    nameAr: "آلات حاسبة علمية",
    descriptionEn: "High-resolution scientific calculators with 552+ functions.",
    descriptionAr: "آلات حاسبة علمية عالية الدقة بأكثر من 552 وظيفة.",
    imageUrl: "/images/category-illustrations/calculators.webp",
    badgeEn: "552 Functions",
    badgeAr: "552 وظيفة",
    sortOrder: 71,
  },
  {
    slug: "desk-calculators",
    parentSlug: "calculators-tech",
    nameEn: "Desk Calculators",
    nameAr: "آلات حاسبة مكتبية",
    descriptionEn: "Mechanical-switch financial calculators for accounting desks.",
    descriptionAr: "آلات حاسبة مالية بمفاتيح ميكانيكية لمكاتب المحاسبة.",
    imageUrl: "/images/category-illustrations/calculators.webp",
    badgeEn: "12-Digit",
    badgeAr: "12 رقماً",
    sortOrder: 72,
  },
  {
    slug: "desk-lamps",
    parentSlug: "calculators-tech",
    nameEn: "Desk Lamps & Study Tech",
    nameAr: "مصابيح مكتبية وتقنيات الدراسة",
    descriptionEn: "Eye-care LED desk lamps with wireless charging and study timers.",
    descriptionAr: "مصابيح LED مكتبية لحماية العين مع شحن لاسلكي ومؤقتات دراسة.",
    imageUrl: "/images/category-illustrations/calculators.webp",
    badgeEn: "CRI 95+",
    badgeAr: "CRI 95+",
    sortOrder: 73,
  },

  {
    slug: "files-folders",
    nameEn: "Files, Folders & Archiving",
    nameAr: "الملفات والأرشيف",
    descriptionEn: "Lever-arch files, hanging folders, document wallets, archive boxes and index dividers.",
    descriptionAr: "ملفات أرشيف، حافظات معلقة، جيوب مستندات، صناديق أرشفة وفواصل فهرسة.",
    imageUrl: "https://images.pexels.com/photos/265667/pexels-photo-265667.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    badgeEn: "Office Filing",
    badgeAr: "تنظيم الأرشيف",
    sortOrder: 8,
  },
  {
    slug: "office-supplies",
    nameEn: "Desk & Office Supplies",
    nameAr: "مستلزمات المكتب اليومية",
    descriptionEn: "Staplers, tape, scissors, clips, sticky notes, punches and everyday desk tools.",
    descriptionAr: "دباسات، شريط لاصق، مقصات، مشابك، أوراق لاصقة، خرامة وأدوات المكتب اليومية.",
    imageUrl: "https://images.pexels.com/photos/159751/book-address-book-learning-learn-159751.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    badgeEn: "Everyday Desk",
    badgeAr: "أدوات يومية",
    sortOrder: 9,
  },
  {
    slug: "school-essentials",
    nameEn: "School Essentials",
    nameAr: "مستلزمات مدرسية",
    descriptionEn: "Geometry sets, lunch boxes, pencil cases, exercise covers and back-to-school kits.",
    descriptionAr: "أطقم هندسة، علب طعام، مقلمات، أغلفة كراسات وباقات العودة للمدرسة.",
    imageUrl: "https://images.pexels.com/photos/414519/pexels-photo-414519.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    badgeEn: "Back to School",
    badgeAr: "العودة للمدرسة",
    sortOrder: 10,
  },
];

export const INITIAL_PRODUCTS: NewProduct[] = [
  // 1. Notebooks
  {
    sku: "NB-ATELIER-01",
    subcategorySlug: "dotted-journals",
    categorySlug: "notebooks",
    titleEn: "Kyoto Linen Hardcover Dotted Journal A5 (Set of 2)",
    titleAr: "دفتر كيوتو بغلافتان من الكتان منقط حجم A5 (طقم من قطعتين)",
    descriptionEn: "Thread-bound lay-flat A5 journals featuring 120gsm ivory Japanese acid-free paper. Zero bleed-through with fountain pens and markers, complete with dual ribbon bookmarks and expandable inner pocket.",
    descriptionAr: "دفتر ملاحظات A5 يفتح بشكل مسطح بالكامل مع ورق ياباني عاجي بوزن 120 جرام خالٍ من الأحماض. مثالي لأقلام الحبر السائل دون تسرب، مزود بشريطين مرجعيين وجيب داخلي.",
    price: 24.90,
    originalPrice: 32.00,
    wholesalePrice: 17.50,
    wholesaleMinQty: 15,
    stock: 140,
    images: [
      "https://images.pexels.com/photos/8251117/pexels-photo-8251117.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/1174122/pexels-photo-1174122.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: true,
    isPromotion: true,
    isHidden: false,
    specsEn: "A5 (148 × 210 mm) • 192 Pages • 120 GSM Ivory Paper",
    specsAr: "حجم A5 • 192 صفحة • ورق عاجي 120 جرام",
  },
  {
    sku: "NB-SPIRAL-02",
    subcategorySlug: "grid-notebooks",
    categorySlug: "notebooks",
    titleEn: "Academic Pro B5 Twin-Wire Grid Notebook Pack (5 pcs)",
    titleAr: "مجموعة دفاتر أكاديمية B5 بسلك مزدوج مربعات (5 قطع)",
    descriptionEn: "Engineered for university lectures and STEM notes. Micro-perforated 100gsm sheets with smart margin rules and color-coded polypropylene waterproof covers.",
    descriptionAr: "مصممة للمحاضرات الجامعية والملاحظات العلمية. أوراق بوزن 100 جرام قابلة للنزع الدقيق مع أغلفة مقاومة للماء بألوان متعددة.",
    price: 19.50,
    originalPrice: 24.00,
    wholesalePrice: 13.80,
    wholesaleMinQty: 20,
    stock: 280,
    images: [
      "https://images.pexels.com/photos/7657377/pexels-photo-7657377.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/867483/pexels-photo-867483.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: false,
    isPromotion: true,
    isHidden: false,
    specsEn: "B5 • 5 Notebooks × 120 Sheets • 100 GSM",
    specsAr: "حجم B5 • 5 دفاتر × 120 ورقة • 100 جرام",
  },
  {
    sku: "NB-PLANNER-03",
    subcategorySlug: "planners-organizers",
    categorySlug: "notebooks",
    titleEn: "Architect Weekly Desk Planner & Sticky Note Folio",
    titleAr: "منظم المكتب الأسبوعي وحافظة الملاحظات اللاصقة",
    descriptionEn: "Undated 52-week panoramic desk pad paired with 6 sizes of pastel architectural index tabs and grid sticky notes.",
    descriptionAr: "منظم مكتبي أسبوعي يكفي لمدة 52 أسبوعاً غير مؤرخ، مرفق مع 6 أحجام من الملاحظات اللاصقة وفواصل التصنيف.",
    price: 16.00,
    originalPrice: null,
    wholesalePrice: 11.20,
    wholesaleMinQty: 25,
    stock: 95,
    images: [
      "https://images.pexels.com/photos/1007025/pexels-photo-1007025.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/5594313/pexels-photo-5594313.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: false,
    isPromotion: false,
    isHidden: false,
    specsEn: "52 Tear-Off Sheets • 450 Sticky Notes Included",
    specsAr: "52 ورقة أسبوعية • 450 ملاحظة لاصقة مرفقة",
  },

  // 2. Fine Writing & Pens
  {
    sku: "WR-FOUNT-01",
    subcategorySlug: "fountain-pens",
    categorySlug: "writing",
    titleEn: "Meister Matte Black & Brass Fountain Pen (Fine Nib)",
    titleAr: "قلم حبر سائل مايستر أسود مطفي ونحاسي (ريشة دقيقة)",
    descriptionEn: "Balanced anodized aluminum barrel with a German iridium-tipped fine nib. Includes refillable piston converter and 2 archival midnight-blue ink cartridges.",
    descriptionAr: "هيكل متوازن من الألمنيوم المؤكسد مع ريشة ألمانية دقيقة مطلية بالإيريديوم. يشمل محول تعبئة وعبوتين من الحبر الأزرق الليلي.",
    price: 38.00,
    originalPrice: 48.00,
    wholesalePrice: 26.50,
    wholesaleMinQty: 10,
    stock: 85,
    images: [
      "/images/new/pen-fountain-01.jpg",
      "https://images.pexels.com/photos/3720819/pexels-photo-3720819.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: true,
    isPromotion: true,
    isHidden: false,
    specsEn: "0.5mm Fine German Nib • Converter Included",
    specsAr: "ريشة ألمانية 0.5 ملم • مرفق مع محول تعبئة",
  },
  {
    sku: "WR-GEL-02",
    subcategorySlug: "gel-rollers",
    categorySlug: "writing",
    titleEn: "Sakura Smooth-Flow 0.5mm Gel Roller Set (12 Colors)",
    titleAr: "طقم أقلام جل ساكورا سريعة الجفاف 0.5 ملم (12 لوناً)",
    descriptionEn: "Instant-dry pigment gel ink prevents smudging for both left-handed and right-handed writers. Ergonomic silicone grip for marathon exam sessions.",
    descriptionAr: "حبر جل صبغي سريع الجفاف يمنع التلطخ لليد اليمنى واليسرى. قبضة سيليكون مريحة لجلسات الدراسة والامتحانات الطويلة.",
    price: 14.90,
    originalPrice: 18.50,
    wholesalePrice: 9.80,
    wholesaleMinQty: 24,
    stock: 320,
    images: [
      "/images/new/gel-sakura-01.jpg",
      "https://images.pexels.com/photos/1099813/pexels-photo-1099813.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: true,
    isPromotion: true,
    isHidden: false,
    specsEn: "12 Pens • 0.5mm Twin-Ball Tip • Waterproof Ink",
    specsAr: "12 قلماً • رأس 0.5 ملم • حبر مقاوم للماء",
  },
  {
    sku: "WR-PASTEL-03",
    subcategorySlug: "highlighters",
    categorySlug: "writing",
    titleEn: "Nordic Dual-Tip Chisel & Fine Pastel Highlighters (8 Pack)",
    titleAr: "مجموعة أقلام تظليل باستيل مزدوجة الرأس (8 ألوان)",
    descriptionEn: "Soft muted tones that highlight key study passages without fatiguing the eyes. Features a 4mm chisel tip and a 1mm underlining tip.",
    descriptionAr: "ألوان باستيل هادئة تبرز النصوص المهمة دون إجهاد العين. مزودة برأس مشطوف 4 ملم ورأس دقيق 1 ملم للتسطير.",
    price: 11.50,
    originalPrice: null,
    wholesalePrice: 7.90,
    wholesaleMinQty: 30,
    stock: 210,
    images: [
      "https://images.pexels.com/photos/5088009/pexels-photo-5088009.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/4144923/pexels-photo-4144923.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: false,
    isPromotion: false,
    isHidden: false,
    specsEn: "8 Muted Tones • Dual Tip (4mm + 1mm)",
    specsAr: "8 ألوان هادئة • رأس مزدوج (4 ملم + 1 ملم)",
  },

  // 3. School Bags & Organizers
  {
    sku: "BG-PACK-01",
    subcategorySlug: "backpacks",
    categorySlug: "bags",
    titleEn: "Oslo Ergonomic 26L Waterproof Scholar & Laptop Backpack",
    titleAr: "حقيبة ظهر أوسلو المريحة المقاومة للماء سعة 26 لتر مع جيب للحاسوب",
    descriptionEn: "Orthopedic breathable back support, dedicated 16-inch suspended laptop compartment, hidden anti-theft pocket, and water-repellent ballistic nylon.",
    descriptionAr: "دعم طبي مريح للظهر قابل للتهوية، قسم مبطن مخصص لحاسوب محمول حتى 16 بوصة، جيب خفي مضاد للسرقة وقماش مقاوم للماء.",
    price: 59.00,
    originalPrice: 75.00,
    wholesalePrice: 41.00,
    wholesaleMinQty: 10,
    stock: 65,
    images: [
      "/images/new/bag-oslo-01.jpg",
      "https://images.pexels.com/photos/2901248/pexels-photo-2901248.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: true,
    isPromotion: true,
    isHidden: false,
    specsEn: "26L Capacity • Fits 16\" Laptop • Water-Repellent",
    specsAr: "سعة 26 لتر • تناسب حاسوب 16 بوصة • مقاومة للماء",
  },
  {
    sku: "BG-CASE-02",
    subcategorySlug: "pencil-cases",
    categorySlug: "bags",
    titleEn: "Expandable Cordura Standing Pencil & Tech Pouch",
    titleAr: "مقلمة وحافظة تقنية قابلة للتوسيع من قماش كوردورا المتين",
    descriptionEn: "Holds up to 45 pens, a scientific calculator, USB cables, and power bank. Folds down into a magnetic standing desk caddy in seconds.",
    descriptionAr: "تتسع لـ 45 قلماً، آلة حاسبة علمية، كابلات USB وشاحن متنقل. تتحول إلى حامل مكتبي قائم بفضل المغناطيس المدمج.",
    price: 18.00,
    originalPrice: 22.00,
    wholesalePrice: 12.50,
    wholesaleMinQty: 20,
    stock: 150,
    images: [
      "https://images.pexels.com/photos/3304855/pexels-photo-3304855.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: false,
    isPromotion: true,
    isHidden: false,
    specsEn: "Cordura 1000D • Magnetic Stand • 6 Mesh Pockets",
    specsAr: "قماش كوردورا متين • قاعدة مغناطيسية • 6 جيوب داخلية",
  },
  {
    sku: "BG-TRAY-03",
    subcategorySlug: "desk-organizers",
    categorySlug: "bags",
    titleEn: "Modular Walnut & Matte Steel Desktop Organizer Suite",
    titleAr: "طقم تنظيم المكتب المعياري من خشب الجوز والفولاذ المطفي",
    descriptionEn: "4-piece interlocking desk tray system for documents, pens, smartphones, and sticky notes with non-slip cork base.",
    descriptionAr: "نظام تنظيم مكتبي مكون من 4 قطع متداخلة للمستندات والأقلام والهواتف الذكية مع قاعدة من الفلين المانع للانزلاق.",
    price: 34.00,
    originalPrice: null,
    wholesalePrice: 24.00,
    wholesaleMinQty: 12,
    stock: 50,
    images: [
      "/images/new/organizer-walnut-01.jpg",
      "https://images.pexels.com/photos/1571453/pexels-photo-1571453.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: false,
    isPromotion: false,
    isHidden: false,
    specsEn: "4 Modular Pieces • Solid Walnut & Powder-Coated Steel",
    specsAr: "4 قطع معيارية • خشب جوز طبيعي وفولاذ مطلي",
  },

  // 4. IT Peripherals & Accessories
  {
    sku: "IT-KEY-01",
    subcategorySlug: "keyboards",
    categorySlug: "it-peripherals",
    titleEn: "KeyChronos Low-Profile Wireless Mechanical Keyboard (Tri-Mode)",
    titleAr: "لوحة مفاتيح ميكانيكية لاسلكية نحيفة كي-كرونوس (ثلاثية الاتصال)",
    descriptionEn: "Connect up to 3 devices via Bluetooth 5.2, 2.4GHz dongle, or USB-C. Hot-swappable tactile quiet switches with warm white backlight and Mac/Windows/Arabic keycap support.",
    descriptionAr: "اتصال بثلاثة أجهزة عبر البلوتوث 5.2 أو مستقبل 2.4 جيجاهرتز أو كابل USB-C. مفاتيح ميكانيكية هادئة مع إضاءة خلفية مريحة ودعم كامل لنظامي ماك وويندوز.",
    price: 89.00,
    originalPrice: 109.00,
    wholesalePrice: 64.00,
    wholesaleMinQty: 8,
    stock: 48,
    images: [
      "https://images.pexels.com/photos/38094551/pexels-photo-38094551.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/12512639/pexels-photo-12512639.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: true,
    isPromotion: true,
    isHidden: false,
    specsEn: "75% Layout • Bluetooth 5.2 + 2.4GHz • 180h Battery",
    specsAr: "حجم 75% مدمج • بلوتوث 5.2 + لاسلكي • بطارية 180 ساعة",
  },
  {
    sku: "IT-MOUSE-02",
    subcategorySlug: "mice",
    categorySlug: "it-peripherals",
    titleEn: "ErgoFlow Master Silent Wireless Mouse (8000 DPI Sensor)",
    titleAr: "فأرة لاسلكية احترافية صامتة إيرغو-فلو (حساس 8000 DPI)",
    descriptionEn: "Sculpted thumb rest with electromagnetic MagSpeed scroll wheel and 95% quieter clicks. Tracks on glass and wood surfaces with USB-C quick charge.",
    descriptionAr: "تصميم مريح لليد مع عجلة تمرير كهرومغناطيسية فائقة السرعة ونقرات صامتة بنسبة 95%. تعمل على كافة الأسطح بما فيها الزجاج مع شحن سريع USB-C.",
    price: 49.00,
    originalPrice: 62.00,
    wholesalePrice: 35.00,
    wholesaleMinQty: 10,
    stock: 75,
    images: [
      "https://images.pexels.com/photos/7151696/pexels-photo-7151696.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/9128856/pexels-photo-9128856.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: true,
    isPromotion: true,
    isHidden: false,
    specsEn: "8000 DPI Glass Sensor • Silent Click • 70-Day Battery",
    specsAr: "حساس 8000 نقطة • نقرات صامتة • بطارية تدوم 70 يوماً",
  },
  {
    sku: "IT-HUB-03",
    subcategorySlug: "hubs-adapters",
    categorySlug: "it-peripherals",
    titleEn: "HyperDock 10-in-1 Aluminum USB-C Hub & 1TB NVMe Enclosure",
    titleAr: "موزع USB-C احترافي 10 في 1 من الألمنيوم مع منفذ HDMI 4K",
    descriptionEn: "Features 4K@60Hz HDMI, Gigabit Ethernet, 100W PD pass-through charging, SD/TF card readers, and 4 high-speed USB 3.2 ports.",
    descriptionAr: "يضم منفذ HDMI بدقة 4K@60Hz، منفذ شبكة جيجابت، شحن سريع بقوة 100 واط، قارئ بطاقات ذاكرة و4 منافذ USB 3.2 فائقة السرعة.",
    price: 44.00,
    originalPrice: null,
    wholesalePrice: 31.00,
    wholesaleMinQty: 10,
    stock: 90,
    images: [
      "/images/new/hub-usbc-01.jpg",
      "https://images.pexels.com/photos/28228014/pexels-photo-28228014.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: false,
    isPromotion: false,
    isHidden: false,
    specsEn: "4K 60Hz HDMI • 100W PD • 10Gbps USB 3.2",
    specsAr: "دعم 4K 60Hz • شحن 100 واط • سرعة نقل 10 جيجابت",
  },

  // 5. Ink, Toner & Consumables
  {
    sku: "INK-TONER-01",
    subcategorySlug: "toner-cartridges",
    categorySlug: "ink-consumables",
    titleEn: "LaserJet Pro High-Yield Black Toner Cartridge (3,500 Pages)",
    titleAr: "خرطوشة تونر ليزر أسود عالية الإنتاجية (3500 صفحة)",
    descriptionEn: "Smart-chip equipped high-density monochrome laser toner producing razor-sharp text and technical diagrams without smudging.",
    descriptionAr: "خرطوشة تونر ليزر مزودة بشريحة ذكية لطباعة نصوص ومخططات هندسية فائقة الوضوح والكثافة دون تلطخ.",
    price: 42.00,
    originalPrice: 54.00,
    wholesalePrice: 29.50,
    wholesaleMinQty: 10,
    stock: 110,
    images: [
      "/images/new/toner-01.jpg",
      "https://images.pexels.com/photos/4526407/pexels-photo-4526407.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: true,
    isPromotion: true,
    isHidden: false,
    specsEn: "3,500 Pages ISO Yield • Smart Chip • Crisp Black",
    specsAr: "إنتاجية 3500 صفحة • شريحة ذكية مدمجة • أسود فاحم",
  },
  {
    sku: "INK-CMYK-02",
    subcategorySlug: "ink-refills",
    categorySlug: "ink-consumables",
    titleEn: "EcoTank CMYK Pigment Refill Ink Multipack (4 × 100ml Bottles)",
    titleAr: "طقم عبوات حبر إيكو-تانك الأربعة CMYK (4 × 100 مل)",
    descriptionEn: "Spill-free auto-stop nozzles delivering up to 7,500 color pages and 6,000 black pages with fade-resistant archival ink.",
    descriptionAr: "فوهات ذكية مانعة للانسكاب توفر طباعة حتى 7500 صفحة ملونة و6000 صفحة سوداء بحبر مقاوم للبهتان.",
    price: 29.90,
    originalPrice: 36.00,
    wholesalePrice: 21.00,
    wholesaleMinQty: 15,
    stock: 160,
    images: [
      "https://images.pexels.com/photos/2330137/pexels-photo-2330137.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/3685538/pexels-photo-3685538.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: false,
    isPromotion: true,
    isHidden: false,
    specsEn: "4 × 100ml (C/M/Y/K) • 7,500 Page Yield",
    specsAr: "4 عبوات × 100 مل • تكفي لطباعة 7500 صفحة",
  },
  {
    sku: "INK-PAPER-03",
    subcategorySlug: "paper-reams",
    categorySlug: "ink-consumables",
    titleEn: "Atelier Ultra-White 90gsm A4 Laser & Inkjet Paper Box (5 Reams / 2500 Sheets)",
    titleAr: "صندوق ورق A4 فائق البياض 90 جرام للطباعة الليزرية والحبرية (5 رزم / 2500 ورقة)",
    descriptionEn: "High-opacity CIE 168 whiteness paper engineered for jam-free high-speed duplex printing in schools, copy centers, and corporate offices.",
    descriptionAr: "ورق فائق البياض والنعومة مصمم للطباعة المزدوجة عالية السرعة دون انحشار، مثالي للمدارس والمكاتب والشركات.",
    price: 32.50,
    originalPrice: null,
    wholesalePrice: 24.90,
    wholesaleMinQty: 10,
    stock: 400,
    images: [
      "/images/new/paper-a4-01.jpg",
      "https://images.pexels.com/photos/4226123/pexels-photo-4226123.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: false,
    isPromotion: false,
    isHidden: false,
    specsEn: "5 Reams × 500 Sheets • 90 GSM • CIE 168 Whiteness",
    specsAr: "5 رزم × 500 ورقة • 90 جرام • بياض ناصع CIE 168",
  },

  // 6. Art & Technical Drafting
  {
    sku: "ART-MARK-01",
    subcategorySlug: "art-markers",
    categorySlug: "art-drafting",
    titleEn: "StudioPro 48-Color Dual-Tip Alcohol Art Markers in Carrying Case",
    titleAr: "حقيبة أقلام ماركر فنية مزدوجة الرأس 48 لوناً",
    descriptionEn: "Blendable alcohol-based ink with Japanese brush and broad chisel nibs for architecture rendering, illustration, and industrial design.",
    descriptionAr: "حبر كحولي قابل للدمج الاحترافي مع رأس فرشاة مرن ورأس عريض للرسم المعماري والتصميم الصناعي والفنون.",
    price: 45.00,
    originalPrice: 58.00,
    wholesalePrice: 31.50,
    wholesaleMinQty: 10,
    stock: 70,
    images: [
      "/images/new/markers-48-01.jpg",
      "https://images.pexels.com/photos/1047540/pexels-photo-1047540.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: true,
    isPromotion: true,
    isHidden: false,
    specsEn: "48 Colors + Blender • Brush & Chisel Nibs",
    specsAr: "48 لوناً + قلم دمج • رأس فرشاة ورأس مشطوف",
  },
  {
    sku: "ART-GEOM-02",
    subcategorySlug: "geometry-sets",
    categorySlug: "art-drafting",
    titleEn: "Precision Solid Brass & Steel Architecture Compass & Drafting Kit",
    titleAr: "طقم الهندسة والرسم التقني الاحترافي من النحاس والفولاذ",
    descriptionEn: "Micro-screw adjustment giant bow compass, extension beam, anodized aluminum scale ruler, and metal protractor in a shockproof tin case.",
    descriptionAr: "فرجار هندسي دقيق ببرغي ضبط ميكروي، مسطرة مقياس من الألمنيوم المؤكسد ومنقلة معدنية داخل حافظة معدنية مقاومة للصدمات.",
    price: 22.00,
    originalPrice: null,
    wholesalePrice: 15.40,
    wholesaleMinQty: 15,
    stock: 115,
    images: [
      "/images/new/compass-brass-01.jpg",
      "https://images.pexels.com/photos/3772509/pexels-photo-3772509.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: false,
    isPromotion: false,
    isHidden: false,
    specsEn: "9-Piece Metal Set • Micro-Adjust Wheel",
    specsAr: "طقم معدني من 9 قطع • عجلة ضبط دقيقة",
  },
  {
    sku: "ART-SKETCH-03",
    subcategorySlug: "sketchpads",
    categorySlug: "art-drafting",
    titleEn: "A4 Cold-Press 300gsm Watercolor & Mixed Media Pad (30 Sheets)",
    titleAr: "كراسة رسم مائي وفنون مختلطة A4 بوزن 300 جرام (30 لوحة)",
    descriptionEn: "100% cotton-blend textured cold-press sheets glued on all 4 sides to prevent warping under heavy washes.",
    descriptionAr: "أوراق فنية بملمس بارد غنية بالقطن بوزن 300 جرام مثالية للألوان المائية والأكريليك والغواش دون تموج الورق.",
    price: 17.50,
    originalPrice: 21.00,
    wholesalePrice: 12.20,
    wholesaleMinQty: 20,
    stock: 90,
    images: [
      "https://images.pexels.com/photos/1028599/pexels-photo-1028599.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/37539/pexels-photo-37539.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: false,
    isPromotion: true,
    isHidden: false,
    specsEn: "A4 • 300 GSM Cold-Press • Acid-Free",
    specsAr: "حجم A4 • وزن 300 جرام • خالٍ من الأحماض",
  },

  // 7. Calculators & Desk Tech
  {
    sku: "CALC-SCI-01",
    subcategorySlug: "scientific-calculators",
    categorySlug: "calculators-tech",
    titleEn: "GraphMaster FX-991EX High-Resolution Scientific Calculator (552 Functions)",
    titleAr: "آلة حاسبة علمية متطورة عالية الدقة (552 وظيفة حسابية)",
    descriptionEn: "Natural textbook display showing matrices, integrals, vectors, and spreadsheet calculations exactly as written in textbooks. Dual solar & battery powered.",
    descriptionAr: "شاشة عرض طبيعية تظهر المعادلات والمصفوفات والتكاملات تماماً كما في الكتب الدراسية. تعمل بالطاقة الشمسية والبطارية.",
    price: 27.50,
    originalPrice: 34.00,
    wholesalePrice: 19.80,
    wholesaleMinQty: 12,
    stock: 130,
    images: [
      "https://images.pexels.com/photos/6232444/pexels-photo-6232444.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/6232426/pexels-photo-6232426.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: true,
    isPromotion: true,
    isHidden: false,
    specsEn: "552 Functions • Natural Textbook LCD • Solar + Battery",
    specsAr: "552 وظيفة علمية • شاشة عرض طبيعية • طاقة مزدوجة",
  },
  {
    sku: "CALC-DESK-02",
    subcategorySlug: "desk-calculators",
    categorySlug: "calculators-tech",
    titleEn: "Tactile Mechanical-Switch 12-Digit Executive Financial Calculator",
    titleAr: "آلة حاسبة مكتبية مالية 12 رقماً بمفاتيح ميكانيكية مريحة",
    descriptionEn: "Tilted large LCD readout with crisp mechanical key switches, tax/margin keys, and brushed aluminum faceplate for accounting desks.",
    descriptionAr: "شاشة LCD كبيرة مائلة مع مفاتيح ميكانيكية سريعة الاستجابة وأزرار حساب الضرائب والربح وواجهة من الألمنيوم المصقول.",
    price: 21.00,
    originalPrice: null,
    wholesalePrice: 14.50,
    wholesaleMinQty: 15,
    stock: 80,
    images: [
      "/images/new/calculator-desk-01.jpg",
      "https://images.pexels.com/photos/399160/pexels-photo-399160.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: false,
    isPromotion: false,
    isHidden: false,
    specsEn: "12-Digit Display • Mechanical Keys • GT & Tax Functions",
    specsAr: "شاشة 12 رقماً • مفاتيح ميكانيكية • وظائف المحاسبة والضرائب",
  },
  {
    sku: "CALC-LAMP-03",
    subcategorySlug: "desk-lamps",
    categorySlug: "calculators-tech",
    titleEn: "Luminaire Eye-Care Architect LED Desk Lamp with Wireless Charger",
    titleAr: "مصباح مكتب LED لحماية العين مع قاعدة شحن لاسلكي للهاتف",
    descriptionEn: "Flicker-free CRI 95+ studio lighting with 5 color temperatures (2700K–6500K), Pomodoro 45-minute study timer, and 15W Qi wireless charging pad.",
    descriptionAr: "إضاءة خالية من الوميض بمعيار CRI 95+ مع 5 درجات حرارة لونية، مؤقت دراسة ذكي وقاعدة شحن لاسلكي سريع بقوة 15 واط.",
    price: 46.00,
    originalPrice: 59.00,
    wholesalePrice: 32.00,
    wholesaleMinQty: 10,
    stock: 60,
    images: [
      "/images/new/lamp-led-01.jpg",
      "https://images.pexels.com/photos/1112598/pexels-photo-1112598.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: false,
    isPromotion: true,
    isHidden: false,
    specsEn: "CRI >95 Eye-Care • 15W Qi Wireless Pad • Study Timer",
    specsAr: "حماية للعين CRI 95+ • شاحن لاسلكي 15 واط • مؤقت دراسة",
  },
  {
    sku: "NB-A4BOX-04",
    categorySlug: "notebooks",
    titleEn: "Office A4 80gsm Copy Paper Carton (5 Reams / 2500 sheets)",
    titleAr: "كرتون ورق تصوير A4 وزن 80 جرام (5 رزم / 2500 ورقة)",
    descriptionEn:
      "Bright-white 80gsm A4 reams for copiers, laser and inkjet. Wrapped 5-ream carton for schools, copy centers and offices.",
    descriptionAr:
      "ورق A4 أبيض ناصع 80 جرام للطابعات والتصوير. كرتون 5 رزم مناسب للمدارس ومراكز النسخ والمكاتب.",
    price: 89.0,
    originalPrice: 105.0,
    wholesalePrice: 72.0,
    wholesaleMinQty: 8,
    stock: 96,
    images: [
      "/images/new/paper-a4-01.jpg",
      "https://images.pexels.com/photos/261763/pexels-photo-261763.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: true,
    isPromotion: true,
    isHidden: false,
    specsEn: "A4 210×297 mm • 80 GSM • 5×500 sheets",
    specsAr: "مقاس A4 • 80 جرام • 5 رزم × 500 ورقة",
  },
  {
    sku: "WR-HIGH-04",
    categorySlug: "writing",
    titleEn: "Pastel Highlighter Wallet (8 pastel + 4 neon)",
    titleAr: "طقم أقلام تظليل باستيل ونيون (12 قلم)",
    descriptionEn:
      "Chisel-tip highlighters that do not bleed through 80gsm paper. Mix of pastel study colours and exam neons.",
    descriptionAr:
      "أقلام تظيل برأس إزميل دون تسرب عبر ورق 80 جرام. ألوان باستيل للدراسة ونيون للامتحانات.",
    price: 14.9,
    originalPrice: 19.5,
    wholesalePrice: 9.8,
    wholesaleMinQty: 24,
    stock: 210,
    images: [
      "/images/new/gel-sakura-01.jpg",
      "https://images.pexels.com/photos/636243/pexels-photo-636243.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: true,
    isPromotion: true,
    isHidden: false,
    specsEn: "12 pens • Chisel 1–5 mm • Quick-dry ink",
    specsAr: "12 قلم • رأس 1–5 مم • حبر سريع الجفاف",
  },
  {
    sku: "BG-TROLLEY-04",
    categorySlug: "bags",
    titleEn: "Rolling School Trolley Backpack 32L with Laptop Sleeve",
    titleAr: "حقيبة مدرسية بعجلات 32 لتر مع جيب لابتوب",
    descriptionEn:
      "Converts from backpack to trolley. Padded 15.6\" sleeve, rain cover and reinforced base for daily school runs.",
    descriptionAr:
      "تتحول من حقيبة ظهر إلى عربة. جيب مبطن 15.6 بوصة وغطاء مطر وقاعدة مقوّاة.",
    price: 129.0,
    originalPrice: 159.0,
    wholesalePrice: 98.0,
    wholesaleMinQty: 8,
    stock: 44,
    images: [
      "/images/new/bag-oslo-01.jpg",
      "/images/cat-bags.jpg",
    ],
    isFeatured: true,
    isPromotion: true,
    isHidden: false,
    specsEn: "32 L • 15.6\" sleeve • Trolley + backpack",
    specsAr: "32 لتر • جيب 15.6 بوصة • عجلات وحقيبة ظهر",
  },
  {
    sku: "IT-SSD-04",
    categorySlug: "it-peripherals",
    titleEn: "Portable NVMe SSD 1TB USB-C 10Gbps",
    titleAr: "قرص SSD محمول 1 تيرابايت USB-C بسرعة 10 جيجابت",
    descriptionEn:
      "Aluminum enclosure, 1050MB/s sequential read, USB-C cable included. For backups, video and exam archives.",
    descriptionAr:
      "علبة ألمنيوم وقراءة حتى 1050 ميجابايت/ث مع كابل USB-C. للنسخ الاحتياطي وأرشيف الامتحانات.",
    price: 245.0,
    originalPrice: 289.0,
    wholesalePrice: 198.0,
    wholesaleMinQty: 6,
    stock: 38,
    images: [
      "/images/new/hub-usbc-01.jpg",
      "https://images.pexels.com/photos/2582937/pexels-photo-2582937.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: true,
    isPromotion: true,
    isHidden: false,
    specsEn: "1 TB NVMe • USB-C 10Gbps • Bus-powered",
    specsAr: "1 تيرابايت NVMe • USB-C 10 جيجابت • بدون محول",
  },
  {
    sku: "INK-DRUM-04",
    categorySlug: "ink-consumables",
    titleEn: "Compatible Laser Drum Unit + Toner Bundle (High Yield)",
    titleAr: "طقم درم ليزر مع تونر عالي الإنتاجية",
    descriptionEn:
      "12,000-page drum and 3,000-page toner for common A4 office lasers. Tested for dense Arabic text.",
    descriptionAr:
      "درم 12 ألف صفحة وتونر 3 آلاف صفحة لطابعات الليزر المكتبية. مختبر للنصوص العربية الكثيفة.",
    price: 78.0,
    originalPrice: 96.0,
    wholesalePrice: 59.0,
    wholesaleMinQty: 10,
    stock: 70,
    images: [
      "/images/new/toner-01.jpg",
      "/images/cat-ink-toner.jpg",
    ],
    isFeatured: false,
    isPromotion: true,
    isHidden: false,
    specsEn: "Drum 12k • Toner 3k • A4 laser",
    specsAr: "درم 12 ألف • تونر 3 آلاف • ليزر A4",
  },
  {
    sku: "ART-SET-04",
    categorySlug: "art-drafting",
    titleEn: "Student Geometry & Drafting Kit in Metal Tin (13 pcs)",
    titleAr: "طقم هندسة و رسم في علبة معدنية (13 قطعة)",
    descriptionEn:
      "Compass, 30/60/90 and 45 triangles, protractor, ruler 30cm, pencils and eraser — exam-ready.",
    descriptionAr:
      "فرجار، مثلثان 30/60 و45، منقلة، مسطرة 30 سم، أقلام رصاص وممحاة — جاهز للامتحانات.",
    price: 18.5,
    originalPrice: 24.0,
    wholesalePrice: 12.9,
    wholesaleMinQty: 20,
    stock: 160,
    images: [
      "/images/new/compass-brass-01.jpg",
      "/images/cat-art-drafting.jpg",
    ],
    isFeatured: true,
    isPromotion: true,
    isHidden: false,
    specsEn: "13 pcs • Metal tin • Exam approved",
    specsAr: "13 قطعة • علبة معدنية • معتمد للامتحانات",
  },
  {
    sku: "CALC-PRINT-04",
    categorySlug: "calculators-tech",
    titleEn: "Printing Desktop Calculator 12-Digit with Paper Roll",
    titleAr: "آلة حاسبة مكتبية طابعة 12 رقماً مع رول ورق",
    descriptionEn:
      "Two-color print (black/red), tax keys and extra paper roll. For cashiers, copy centers and school accounts.",
    descriptionAr:
      "طباعة بلونين أسود/أحمر ومفاتيح ضرائب ورول ورق إضافي. للصناديق ومراكز النسخ ومحاسبة المدارس.",
    price: 54.0,
    originalPrice: 69.0,
    wholesalePrice: 41.0,
    wholesaleMinQty: 8,
    stock: 52,
    images: [
      "/images/new/calculator-desk-01.jpg",
      "/images/cat-calculators.jpg",
    ],
    isFeatured: false,
    isPromotion: true,
    isHidden: false,
    specsEn: "12-digit • 2-color print • AC + battery",
    specsAr: "12 رقماً • طباعة بلونين • كهرباء وبطارية",
  },
  {
    sku: "FL-ARCH-01",
    categorySlug: "files-folders",
    titleEn: "Lever-Arch File A4 75mm — Pack of 10",
    titleAr: "ملف أرشيف ذراع A4 سمك 75 مم — طقم 10",
    descriptionEn: "Board lever-arch files with metal finger ring and spine label. Standard for school and company archives.",
    descriptionAr: "ملفات كرتون بقفل ذراع وحلقة معدنية وبطاقة كعب. المعيار لأرشيف المدارس والشركات.",
    price: 42.0,
    originalPrice: 52.0,
    wholesalePrice: 31.5,
    wholesaleMinQty: 12,
    stock: 120,
    images: [
      "https://images.pexels.com/photos/265667/pexels-photo-265667.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/159751/book-address-book-learning-learn-159751.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: true,
    isPromotion: true,
    isHidden: false,
    specsEn: "A4 • 75 mm • Pack of 10",
    specsAr: "A4 • 75 مم • 10 ملفات",
  },
  {
    sku: "FL-HANG-02",
    categorySlug: "files-folders",
    titleEn: "Hanging File Folders Foolscap — Box of 25",
    titleAr: "حافظات معلقة فولسكاب — علبة 25",
    descriptionEn: "Reinforced hanging folders with clear tabs for cabinet drawers.",
    descriptionAr: "حافظات معلقة مقوّاة مع فواصل شفافة لأدراج الخزائن.",
    price: 28.5,
    originalPrice: 34.0,
    wholesalePrice: 21.0,
    wholesaleMinQty: 8,
    stock: 80,
    images: [
      "https://images.pexels.com/photos/265667/pexels-photo-265667.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: false,
    isPromotion: true,
    isHidden: false,
    specsEn: "Foolscap • 25 pcs • Metal rails",
    specsAr: "فولسكاب • 25 قطعة • قضبان معدنية",
  },
  {
    sku: "FL-BOX-03",
    categorySlug: "files-folders",
    titleEn: "Archive Storage Box with Lid — Pack of 5",
    titleAr: "صندوق أرشيف بغطاء — طقم 5",
    descriptionEn: "Heavy-duty corrugated archive boxes, A4/Foolscap, stacking lid.",
    descriptionAr: "صناديق أرشيف كرتون مقوّى بمقاس A4 مع غطاء قابل للرص.",
    price: 36.0,
    originalPrice: 44.0,
    wholesalePrice: 26.0,
    wholesaleMinQty: 10,
    stock: 64,
    images: [
      "https://images.pexels.com/photos/4246120/pexels-photo-4246120.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: true,
    isPromotion: false,
    isHidden: false,
    specsEn: "A4/Foolscap • 5 boxes • Stackable",
    specsAr: "A4 • 5 صناديق • قابل للرص",
  },
  {
    sku: "OF-STAP-01",
    categorySlug: "office-supplies",
    titleEn: "Metal Desk Stapler 24/6 + 2000 Staples",
    titleAr: "دباسة مكتبية معدنية 24/6 مع 2000 دبوس",
    descriptionEn: "Full-strip metal stapler, 20-sheet capacity, includes a box of 24/6 staples.",
    descriptionAr: "دباسة معدنية كاملة الشريط لـ 20 ورقة مع علبة دبابيس 24/6.",
    price: 16.9,
    originalPrice: 21.0,
    wholesalePrice: 11.5,
    wholesaleMinQty: 20,
    stock: 180,
    images: [
      "https://images.pexels.com/photos/636243/pexels-photo-636243.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/159751/book-address-book-learning-learn-159751.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: true,
    isPromotion: true,
    isHidden: false,
    specsEn: "24/6 • 20 sheets • Metal body",
    specsAr: "24/6 • 20 ورقة • جسم معدني",
  },
  {
    sku: "OF-TAPE-02",
    categorySlug: "office-supplies",
    titleEn: "Clear Tape Dispenser + 6 Rolls 18mm",
    titleAr: "قاعدة شريط لاصق مع 6 رولات 18 مم",
    descriptionEn: "Weighted desktop dispenser with 6 crystal tapes for packing and office use.",
    descriptionAr: "قاعدة مكتبية ثقيلة مع 6 رولات شفافة للتغليف والمكتب.",
    price: 19.5,
    originalPrice: 24.0,
    wholesalePrice: 13.8,
    wholesaleMinQty: 16,
    stock: 110,
    images: [
      "https://images.pexels.com/photos/4792285/pexels-photo-4792285.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: false,
    isPromotion: true,
    isHidden: false,
    specsEn: "18 mm × 33 m • 6 rolls • Weighted base",
    specsAr: "18 مم × 33 م • 6 رولات • قاعدة ثقيلة",
  },
  {
    sku: "OF-NOTE-03",
    categorySlug: "office-supplies",
    titleEn: "Sticky Notes Cube 76×76 mm — 5 colours",
    titleAr: "مكعب أوراق لاصقة 76×76 مم — 5 ألوان",
    descriptionEn: "500-sheet pastel cube, residue-free adhesive, for meetings and study.",
    descriptionAr: "مكعب 500 ورقة باستيل بلا بقايا لاصق، للاجتماعات والدراسة.",
    price: 9.9,
    originalPrice: 12.5,
    wholesalePrice: 6.8,
    wholesaleMinQty: 24,
    stock: 240,
    images: [
      "https://images.pexels.com/photos/636243/pexels-photo-636243.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: true,
    isPromotion: true,
    isHidden: false,
    specsEn: "76×76 mm • 500 sheets • 5 colours",
    specsAr: "76×76 مم • 500 ورقة • 5 ألوان",
  },
  {
    sku: "OF-PUNCH-04",
    categorySlug: "office-supplies",
    titleEn: "Heavy-Duty 2-Hole Punch 40 Sheets",
    titleAr: "خرامة مكتبية ثقيلة فتحتين — 40 ورقة",
    descriptionEn: "Metal 2-hole punch with paper guide, 40-sheet capacity, lock-down handle.",
    descriptionAr: "خرامة معدنية فتحتين بسعة 40 ورقة ومقبض قفل.",
    price: 27.0,
    originalPrice: 33.0,
    wholesalePrice: 19.5,
    wholesaleMinQty: 12,
    stock: 70,
    images: [
      "https://images.pexels.com/photos/159751/book-address-book-learning-learn-159751.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: false,
    isPromotion: false,
    isHidden: false,
    specsEn: "2-hole • 40 sheets • Metal",
    specsAr: "فتحتان • 40 ورقة • معدن",
  },
  {
    sku: "SC-CASE-01",
    categorySlug: "school-essentials",
    titleEn: "3-Zip Pencil Case with Name Window",
    titleAr: "مقلمة ثلاث سحّابات مع نافذة الاسم",
    descriptionEn: "Hard-bottom pencil case, three compartments, ID window. Fits 15 cm ruler.",
    descriptionAr: "مقلمة بقاعدة صلبة وثلاث جيوب ونافذة اسم. تتسع لمسطرة 15 سم.",
    price: 22.0,
    originalPrice: 28.0,
    wholesalePrice: 15.5,
    wholesaleMinQty: 16,
    stock: 150,
    images: [
      "https://images.pexels.com/photos/414519/pexels-photo-414519.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "/images/new/bag-oslo-01.jpg",
    ],
    isFeatured: true,
    isPromotion: true,
    isHidden: false,
    specsEn: "3 zips • Name window • 22 cm",
    specsAr: "3 سحّابات • نافذة اسم • 22 سم",
  },
  {
    sku: "SC-KIT-02",
    categorySlug: "school-essentials",
    titleEn: "Back-to-School Starter Kit (12 items)",
    titleAr: "باقة العودة للمدرسة (12 قطعة)",
    descriptionEn: "Notebooks, pens, pencils, eraser, sharpener, ruler, glue stick and colours — one bag for year start.",
    descriptionAr: "دفاتر، أقلام، رصاص، ممحاة، مبراة، مسطرة، صمغ وألوان — حقيبة بداية السنة.",
    price: 49.0,
    originalPrice: 64.0,
    wholesalePrice: 36.0,
    wholesaleMinQty: 10,
    stock: 90,
    images: [
      "https://images.pexels.com/photos/414519/pexels-photo-414519.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "/images/new/hero-bts-01.jpg",
    ],
    isFeatured: true,
    isPromotion: true,
    isHidden: false,
    specsEn: "12 items • Primary / middle school",
    specsAr: "12 قطعة • ابتدائي وإعدادي",
  },
  {
    sku: "SC-COVER-03",
    categorySlug: "school-essentials",
    titleEn: "Transparent Book Covers A4 / A5 — Pack of 20",
    titleAr: "أغلفة كراسات شفافة A4 / A5 — 20 قطعة",
    descriptionEn: "Crystal PVC covers with name label, mix of A4 and A5.",
    descriptionAr: "أغلفة PVC شفافة مع بطاقة اسم، مقاسان A4 و A5.",
    price: 14.5,
    originalPrice: 18.0,
    wholesalePrice: 9.9,
    wholesaleMinQty: 20,
    stock: 200,
    images: [
      "/images/new/paper-a4-01.jpg",
      "https://images.pexels.com/photos/261763/pexels-photo-261763.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: false,
    isPromotion: true,
    isHidden: false,
    specsEn: "10×A4 + 10×A5 • PVC",
    specsAr: "10 A4 + 10 A5 • PVC",
  },
];

export const INITIAL_STORE_SETTINGS: NewStoreSettings = {
  storeNameEn: "Al Manhaj Company for Stationery",
  storeNameAr: "شركة المنهج للقرطاسية",
  announcementEnabled: true,
  announcementEn:
    "توصيل مجاني داخل طرابلس فوق 1900 د.ل — Free Standard Shipping $60+ →",
  announcementAr:
    "توصيل مجاني داخل طرابلس فوق 1900 د.ل — Free Standard Shipping $60+ →",
  announcementShortEn: "توصيل مجاني 1900 د.ل+ →",
  announcementShortAr: "توصيل مجاني 1900 د.ل+ →",
  announcementNoteEn: "البيفي، طرابلس • 0912145050",
  announcementNoteAr: "البيفي، طرابلس • 0912145050",
  headerTaglineEn: "PAPER • STATIONERY • ATELIER • TRIPOLI",
  headerTaglineAr: "ورق • قرطاسية • أدوات هندسية • طرابلس",
  storefrontImage: "/images/new/main-storefront-hq.jpg",
  storefrontBadgeEn: "Al Bivi, Tripoli, Libya",
  storefrontBadgeAr: "البيفي، طرابلس، ليبيا",
  storefrontTitleEn: "Al Manhaj Company for Stationery",
  storefrontTitleAr: "شركة المنهج للقرطاسية",
  storefrontSubtitleEn: "Almanhaj for Stationery and Computer Equipment",
  storefrontSubtitleAr: "شركة المنهج للقرطاسية ومعدات الحاسوب",
  storefrontDescriptionEn:
    "Office tools • Engineering equipment • School supplies • Cabinets • Printer ink & computer equipment",
  storefrontDescriptionAr:
    "أدوات مكتبية • معدات هندسية • أدوات مدرسية • خزائن مختلفة • حبر طابعات ومعدات الحاسوب",
  taglineEn:
    "Office Tools • Engineering Equipment • School Supplies • Cabinets • Printer Ink & Computer Equipment",
  taglineAr:
    "أدوات مكتبية • معدات هندسية • أدوات مدرسية • خزائن مختلفة • حبر طابعات",
  whatsappNumber: "218912145050",
  contactEmail: "info@almanhaj.ly",
  contactPhone: "+218 91-214-5050",
  addressEn: "Al Bivi, Tripoli, Libya",
  addressAr: "البيفي، طرابلس، ليبيا",
  workingHoursEn: "Sat – Thu: 09:00 – 21:00",
  workingHoursAr: "السبت – الخميس: 09:00 صباحاً – 09:00 مساءً",
  currencyEn: "LYD",
  currencyAr: "د.ل",
  wholesaleDiscountTier1Pct: 15,
  wholesaleDiscountTier2Pct: 22,
  wholesaleDiscountTier3Pct: 30,
  wholesaleConditionsEn:
    "Enjoy instant B2B & institutional pricing for schools, universities, copy centers, and companies across Libya. Orders of 10+ units per SKU unlock Wholesale Price automatically. Free delivery in Tripoli on orders over 1,900 LYD and dedicated pro-forma invoicing via WhatsApp +218 91-214-5050.",
  wholesaleConditionsAr:
    "استفد من أسعار الجملة الفورية للمدارس والجامعات ومراكز الطباعة والشركات في ليبيا. الطلبات ابتداءً من 10 قطع للصنف الواحد تفعّل سعر الجملة تلقائياً، مع توصيل مجاني داخل طرابلس للطلبيات فوق 1,900 د.ل وفوترة احترافية مباشرة عبر واتساب 0912145050.",
  defaultTheme: "cyber",
  heroSlides: [
    {
      id: "slide-1",
      imageUrl: "/images/new/hero-stationery-01.jpg",
      badgeEn: "2026 Academic & Studio Collection",
      badgeAr: "مجموعة الموسم الدراسي والاستوديو 2026",
      titleEn: "Tactile Paper Goods & Precision Writing Tools",
      titleAr: "قرطاسية فاخرة وأدوات كتابة وهندسة عالية الدقة",
      subtitleEn:
        "From 120gsm Japanese dotted notebooks to German-nib fountain pens — crafted for students, architects, and creators.",
      subtitleAr:
        "من الدفاتر اليابانية الفاخرة بوزن 120 جرام إلى أقلام الحبر السائل والأدوات الهندسية المصممة للطلاب والمبدعين.",
      ctaEn: "Explore Stationery",
      ctaAr: "استكشف القرطاسية",
      targetCategory: "notebooks",
    },
    {
      id: "slide-2",
      imageUrl: "/images/new/hero-it-tech-01.jpg",
      badgeEn: "IT Peripherals & Office Consumables",
      badgeAr: "معدات المعلوماتية والأحبار والمستهلكات",
      titleEn: "High-Performance Workspace Tech & Original Toners",
      titleAr: "ملحقات الحاسوب الاحترافية وأحبار الطباعة عالية الإنتاجية",
      subtitleEn:
        "Equip your study desk or company office with wireless mechanical keyboards, ergonomic mice, and high-yield laser toners.",
      subtitleAr:
        "جهّز مكتبك أو مؤسستك بلوحات المفاتيح الميكانيكية اللاسلكية والفئران المريحة وخراطيش الليزر والأوراق الفاخرة.",
      ctaEn: "Shop IT & Consumables",
      ctaAr: "تسوّق التقنية والأحبار",
      targetCategory: "it-peripherals",
    },
    {
      id: "slide-3",
      imageUrl: "/images/new/hero-bts-01.jpg",
      badgeEn: "Retail & Wholesale B2B Supply",
      badgeAr: "البيع بالتقسيط وبالجملة للمؤسسات والمدارس",
      titleEn: "Complete Back-to-School & Bulk Institutional Packs",
      titleAr: "تجهيز شامل للعودة المدرسية وعروض خاصة للبيع بالجملة",
      subtitleEn:
        "Up to 30% wholesale discounts on school bags, scientific calculators, art markers, and A4 paper boxes.",
      subtitleAr:
        "خصومات تصل إلى 30% لطلبات الجملة على الحقائب المدرسية والآلات الحاسبة العلمية وأدوات الرسم وصناديق الورق.",
      ctaEn: "View Wholesale Offers",
      ctaAr: "عروض البيع بالجملة",
      targetCategory: "bags",
    },
  ],
  landscapeBanner: {
    imageUrl: "/images/new/landscape-01.jpg",
    badgeEn: "THE COMPLETE STUDIO & OFFICE ECOSYSTEM",
    badgeAr: "منظومة متكاملة للدراسة والمكاتب الحديثة",
    titleEn: "Where Traditional Paper Craftsmanship Meets Digital Productivity",
    titleAr: "حيث تلتقي حرفية الورق الفاخر مع أحدث تقنيات المكتب الرقمي",
    subtitleEn:
      "Every item in our catalog is tested for durability, archival quality, and daily ergonomics — available individually or in wholesale cartons with instant WhatsApp ordering.",
    subtitleAr:
      "كل منتج في كتالوجنا مختبر بعناية لضمان المتانة والجودة العالية والراحة اليومية — متوفر بالقطعة أو بكميات الجملة مع طلب فوري ومباشر عبر واتساب.",
    ctaEn: "Open Full Master Catalog",
    ctaAr: "افتح الكتالوج الشامل",
  },
  // ----- Pied de page : barre légale (modifiable depuis لوحة الإدارة) -----
  complianceEnabled: true,
  complianceStatusEn:
    "Store registration with the Mawthooq platform (Ministry of Economy) is in progress",
  complianceStatusAr:
    "متجر قيد التسجيل في منصة موثوق بوزارة الاقتصاد والتجارة",
  commercialRegistry: "",
  mawthooqLicense: "",
  paymentNoticeEn:
    "Cash on delivery and bank transfer are available today — electronic payment (LYPay / Moamalat / Tadawul / Masarat) will be enabled once the Mawthooq licence is issued, in line with the Central Bank of Libya instructions (Circular 7/2020).",
  paymentNoticeAr:
    "الدفع عند التسليم و عبر التحويل المصرفي حالياً — الدفع الإلكتروني (LYPay / معاملات / تداول / مسارات) يُفعّل بعد إصدار ترخيص موثوق حسب تعليمات مصرف ليبيا المركزي (منشور 7/2020).",
  copyrightEn:
    "© {year} Al Manhaj Company for Stationery — All rights reserved • Al Bivi, Tripoli — Libyan Dinar (LYD)",
  copyrightAr:
    "© {year} شركة المنهج للقرطاسية — جميع الحقوق محفوظة • البيفي، طرابلس — الدينار الليبي",
  paymentProvidersUrl: "https://cbl.gov.ly/electronic-payment/",
};

/** Seed rows have no serial ids — attach stable ones for React keys and cart ops. */
export function hydrateFallbackStore() {
  return {
    categories: INITIAL_CATEGORIES.map((category, index) => ({
      ...category,
      id: index + 1,
    })),
    products: INITIAL_PRODUCTS.map((product, index) => ({
      ...product,
      id: index + 1,
    })),
    settings: { ...INITIAL_STORE_SETTINGS, id: 1 },
  };
}

